services:
  onedesk-dev:
    build:
      context: .
      args:
        BUILD_TIME: ${BUILD_TIME:-unknown}
    ports:
      - "5002:5000"
    env_file:
      - .env.dev
    volumes:
      - db_data:/app/instance
      - uploads:/app/static/uploads
      - logs:/app/logs
    restart: unless-stopped

volumes:
  db_data:
  uploads:
  logs:
